#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$ADDITIONAL_USER" WITH PASSWORD '$ADDITIONAL_USER_PASSWORD';
    CREATE DATABASE "$ADDITIONAL_DATABASE";
    GRANT ALL PRIVILEGES ON DATABASE "$ADDITIONAL_DATABASE" TO "$ADDITIONAL_USER";
    ALTER USER "$ADDITIONAL_USER" SUPERUSER; 
EOSQL
